# Generated by Django 4.1.2 on 2022-10-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_module', '0004_alter_rating_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='movie_rating_score', to='movies_module.rating', verbose_name='امتیاز'),
            preserve_default=False,
        ),
    ]
