# Generated by Django 4.1.2 on 2022-10-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_module', '0006_alter_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.ForeignKey(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], on_delete=django.db.models.deletion.CASCADE, related_name='movie_rating_score', to='movies_module.rating', verbose_name='امتیاز'),
        ),
    ]
