# Generated by Django 4.2.7 on 2023-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_module', '0010_remove_movies_rating_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviescategory',
            name='popularity',
            field=models.IntegerField(default=98, verbose_name='محبوبیت'),
        ),
    ]
