# Generated by Django 4.2.7 on 2023-12-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_module', '0011_moviescategory_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ManyToManyField(to='movies_module.moviescategory', verbose_name='دسته بندی ها'),
        ),
    ]
