# Generated by Django 4.2.7 on 2023-12-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_module', '0012_alter_movies_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='movies_module.moviescategory', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
