# Generated by Django 4.2.7 on 2023-12-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_module', '0013_remove_movies_category_movies_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.ManyToManyField(to='movies_module.moviescategory', verbose_name='دسته بندی ها'),
        ),
    ]
