# Generated by Django 4.2.7 on 2023-12-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_module', '0014_remove_movies_category_movies_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.AddField(
            model_name='movies',
            name='score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies_module.rating', verbose_name='امتیاز'),
            preserve_default=False,
        ),
    ]
