# Generated by Django 4.2.7 on 2023-12-05 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_module', '0016_alter_rating_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='score',
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='movies_module.movies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
